POST http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Category 2",
    "description": "Category 2 description"
}

###

GET http://localhost:8080/category/e449c666-8a38-4058-8db7-a642200e42d4 HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/category HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

POST http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

{
    "name": "Product 1",
    "description": "Product 1 description",
    "price": 100,
    "image_url": "http://www.google.com",
    "category_id": "6b291e52-9aa1-43d4-a80f-aa005718e5c6"
}

###

GET http://localhost:8080/product HTTP/1.1
Host: localhost:8080
Content-Type: application/json

###

GET http://localhost:8080/product/0afa7630-4fc1-4d69-beed-4f8f15becadc HTTP/1.1
Host: localhost:8080
Content-Type: application/json

### 

GET http://localhost:8080/product/category/6b4c28f4-6831-495a-9444-19c93452faa3 HTTP/1.1
Host: localhost:8080
Content-Type: application/json